name: JSON Linter

on:
  push:
  workflow_dispatch:

jobs:
  json_linter_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start JSON Linter
        run: |
          npm i -g @prantlf/jsonlint
          jsonlint "**/*.json"
